### What is numpy?

Numpy is mainly a library to allow you to manipulate scalar, vectors, matrices, tensors, etc. and provide you with linear algebra operations for these objects

In [2]:
import numpy as np

#### Numpy vector (1d)

In [3]:
# How to declare a 1d vector in numpy
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


In [4]:
# The size of the vector
print(numpy_array.shape)

(5,)


In [5]:
# Access one element from the vector as if it was an array
print(numpy_array[1])

2


In [6]:
# Numpy arrays are mutable (can be changed)
numpy_array[1] = 10
print(numpy_array)

[ 1 10  3  4  5]


#### Numpy matrices (2d)

In [7]:
# How to declare a 2d matrix in numpy
numpy_array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(numpy_array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
# Size of the matrix (rows x columns)
print(numpy_array_2d.shape)

(2, 4)


In [9]:
# Access one element in the matrix
print(numpy_array_2d[1,2])

7


In [10]:
# Again, numpy arrays are mutable (can be changed)
numpy_array_2d[1,2] = 10
print(numpy_array_2d)

[[ 1  2  3  4]
 [ 5  6 10  8]]


#### Numpy tensors (3d or more)

In [11]:
# How to declare a 3d tensor in numpy
numpy_array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(numpy_array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
# Size of the tensor (depth x rows x columns)
print(numpy_array_3d.shape)

(2, 2, 3)


In [13]:
# Access one element of the tensor
print(numpy_array_3d[1,1,2])

12


### Special numpy arrays

In [14]:
# An array full of zeros with a specific shape
zero_mat = np.zeros((2,2))
print(zero_mat)

[[0. 0.]
 [0. 0.]]


In [15]:
# An array full of ones with a specific shape
ones_mat = np.ones((3,3))
print(ones_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# An array with the shape of the identity given a shape (it is always a square matrix)
eye_mat = np.eye(4)
print(eye_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# An array with a specific shape and a specific number in all entries
full_mat = np.full((5,5),12)
print(full_mat)

[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]


In [19]:
range_array = np.arange(10) # np.arange(stop) starts at 0 with step size = 1
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
range_array_2 = np.arange(10,20) # np.arange(start,stop) with step size = 1
print(range_array_2)

[10 11 12 13 14 15 16 17 18 19]


In [21]:
range_array_3 = np.arange(4,7,0.5) # np.arange(start,stop,step size)
print(range_array_3)

[4.  4.5 5.  5.5 6.  6.5]


In [22]:
x = np.arange(9) # x = [0 1 2 3 4 5 6 7 8]
reshaped_x = x.reshape(3,3) # reshape x into a different shape (Here from (9,) to (3,3)). 
#Note that the number of elements before and after reshaping need to be equal (Here you can't reshape x into (4,3))

print(reshaped_x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Random

See more methods at the [numpy random documentation](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

In [18]:
# An array of random numbers with a specific shape
random_mat = np.random.random((3,5))
print(random_mat)

[[0.41670225 0.35525697 0.66490292 0.25350153 0.63058386]
 [0.63371797 0.89046837 0.83751163 0.05840217 0.49382081]
 [0.38119983 0.22312127 0.44386576 0.93389981 0.15277685]]


In [74]:
mean = 2
standard_deviation = 3
x = np.random.normal(mean,standard_deviation,(4,4))
print(x)
print("X has mean = {}".format(x.mean()))
print("X has standard deviation = {}".format(np.std(x)))

[[-3.38809982 -2.07352819 -0.82527833 -0.73228142]
 [ 1.40208473  7.0376285   2.38385837  9.63902907]
 [ 0.36767453  5.38871898 -2.30692696  4.97315775]
 [-2.68914747  0.89350176 -1.13813788  0.50980954]]
X has mean = 1.215128945973523
X has standard deviation = 3.6423891089033105


In [78]:
x = np.random.uniform(low=10.0, high=100.0, size=(5,5))
print(x)

[[84.88001404 89.48524213 52.22039177 46.04393944 60.75681647]
 [39.17718118 72.66035015 88.66714812 89.87755353 10.06299562]
 [94.17243677 53.58151578 67.3093529  69.68660398 81.36078462]
 [79.58422506 89.96890213 92.92821877 71.26431369 46.2532707 ]
 [89.71527709 14.42146267 11.99565913 55.84117021 80.79346724]]


In [75]:
x = np.random.randint(low=5, high=100, size=(5,5))
print(x)

[[65  6 77 36 68]
 [58 71 56 27 13]
 [60 75 22 14 29]
 [69 53 53 25 50]
 [59 64 48 14 62]]


In [80]:
x = np.arange(100)
y = np.random.permutation(x)
print(y)

[80 28 48 32 73 46 67 12 95  4 70  5 98 34 45  8 26 51 53 76 13 35 14 20
 75 29 88 42 54 65 99 38 72 85 21 68 18 74 83 89 90 44 63 94 79 31 22 62
 55 52  2 25 47 10 71 58 30 11 97 93 69 96 78 57 64 66 37 23  1 49 59 19
  9  3 27 40  7 17 91 86 60 43  0 24 82 39 61 81 87 84 15  6 92 33 50 77
 56 41 36 16]


In [81]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [82]:
np.random.shuffle(x)
print(x)

[ 9 60 35 58 36 26 21 59 53 61 89 78 69 64 56  5 84 25 22 43 85 54 62 91
 51 81 12 42 74 44 95 47 49 63  7  8 80 73 57  0 67 28 75 93 82 65 17 39
 27  6 55 31 20 37  2 98 23 90 15  3 13 34 99 41 29 76 86 48 94 88 19 52
 96 10 11 68 16 32  1 24 18 83 40 70 97 92 46 30 71 66 72 50 14 38 79 33
  4 45 87 77]


In [93]:
print(np.random.choice(x))

96


In [148]:
np.random.seed(2)

In [149]:
x = np.random.randint(low=5, high=100, size=(5,5))
print(x)

[[45 20 77 27 48]
 [87 80 12 39 54]
 [80 90 52 68 36]
 [95 25 42 44 72]
 [ 9 47 56 43 38]]


In [150]:
x = np.random.randint(low=5, high=100, size=(5,5))
print(x)

[[63 72 74 93 73]
 [51 75 88 36 71]
 [85 57 81 55  9]
 [95 68 84 54 44]
 [51 13 55 20 13]]


## Slice indexing

## Data types
* int32
* int64
* float64

In [23]:
int32_array = np.array([1,2,3]) #type is auto assigned
print(int32_array.dtype)

int32


In [24]:
int64_array = np.array([1,2,3],dtype=np.int64) # type is defined manually
print(int64_array.dtype)

int64


In [25]:
float32_array = np.array([1.0,2.0,3.0],dtype=np.float32) # type is defined manually
print(float32_array.dtype)

float32


In [26]:
float64_array = np.array([1.0,2.0,3.0]) # type is auto assigned (default float is float64 == double)
print(float64_array.dtype)

float64


In [27]:
float_to_int_array = np.array([1.2,1.5,1.7,1.999,2.0],dtype=np.int32) # convert an array to int does the operation floor on all elements
print(float_to_int_array)

[1 1 1 1 2]


## Operations

### Basic operations

In [28]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [29]:
print(x+y) # you can also use np.add(x,y)

[5 7 9]


In [30]:
print(x-y) # you can also use np.subtract(x,y)

[-3 -3 -3]


In [31]:
print(x*y) # you can also use np.multiply(x,y)

[ 4 10 18]


In [32]:
print(5*x) # multiplying by a scalar, you can also use np.multiply(5,x)

[ 5 10 15]


In [33]:
print(x/y) # you can also use np.divide(x,y)

[0.25 0.4  0.5 ]


In [34]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


In [35]:
print(np.exp(x)) # e**x

[ 2.71828183  7.3890561  20.08553692]


In [36]:
print(x.sum()) # sum all of the elements in x

6


In [37]:
print(np.sort([5,4,2,6,1]))

[1 2 4 5 6]


In [38]:
print(np.argsort([5,4,2,6,1]))

[4 2 1 0 3]


### Statistical operations

In [39]:
x = np.array([1,2,3,3])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("X =")
print(x)
print()
print("Y =")
print(y)

X =
[1 2 3 3]

Y =
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
print(x.mean())

2.25


In [41]:
print(y.mean())

5.0


In [42]:
print(y.mean(axis=1))

[2. 5. 8.]


In [43]:
print(y.mean(axis=0))

[4. 5. 6.]


In [44]:
print(np.median(y,axis=1))

[2. 5. 8.]


In [45]:
print(x.std())

0.82915619758885


In [46]:
print(x.var())

0.6875


In [51]:
print(np.max(x))

3


In [52]:
print(np.argmax(x))

2


In [53]:
print(np.min(x))

1


In [54]:
print(np.argmin(x))

0


### Sets

In [45]:
x = np.array([1,9,1,2,3,3,4,6,6,5,8,8,1,2,4])

In [46]:
unique_x = np.unique(x) # gets the unique elements in x and sorts them
print(unique_x)

[1 2 3 4 5 6 8 9]


In [47]:
set_1 = np.array([1, 5, 12, "circle", 9, "triangle"])
set_2 = np.array(["square",5,"triangle",9,9,4,"rectangle"])

In [48]:
print(np.union1d(set_1,set_2))

['5' '9' 'triangle']


In [49]:
print(np.intersect1d(set_1,set_2))

['5' '9' 'triangle']


In [50]:
print(np.setdiff1d(set_1,set_2))

['1' '12' 'circle']


In [51]:
print(np.in1d(set_1,set_2))

[False  True False False  True  True]


### Linear Algebra / Matrices

In [69]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("X =")
print(x)
print()
print("Y =")
print(y)

X =
[[1 2]
 [3 4]]

Y =
[[5 6]
 [7 8]]


In [70]:
print("X*Y =")
print(np.dot(x,y)) # matrix multiplication not element wise multiplication

X*Y =
[[19 22]
 [43 50]]


In [71]:
print(x*y) # Notice the difference between "x*y" and "np.dot(x,y)"

[[ 5 12]
 [21 32]]


In [73]:
print(np.transpose(x)) # The transpose of the matrix x

[[1 3]
 [2 4]]


In [74]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x)
print()
print("Y =")
print(y)

[1 2 3]

Y =
[4 5 6]


In [75]:
print(np.dot(x,y)) # dot product of the two vectors

32


In [76]:
# To multiply 2 vectors and get a matrix they need to be matrices (i.e [[you vector]]). Instead of [1 2 3] use [[1 2 3]]
print(np.dot(np.transpose([x]),[y]))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Broadcasting

In [61]:
x = np.zeros((4,4))
row_to_add = np.array([1,2,3,4])

In [62]:
y = x + row_to_add
print(y)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [69]:
col_to_add = np.transpose([row_to_add])
y = x + col_to_add
print(y)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [70]:
y = x + 2
print(y)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


## Combining Arrays

## Saving and loading arrays

In [55]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [56]:
np.save("numpy_array",x)

In [57]:
y = np.load("numpy_array.npy")
print(y)

[[1 2 3]
 [4 5 6]]


In [58]:
np.savetxt("numpy_array.txt",X=x,delimiter=",")

In [59]:
y = np.loadtxt("numpy_array.txt",delimiter=",")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]


## Boolean indexing and masks